@startuml

<style>
caption {
FontSize 20
}
</style>

caption Json New startegy : load file - obsolete

start
'skinparam ConditionEndStyle hline

:fileLoaded = false;

:compute config4.json Hash to H0|
:compute config4copy1.json Hash to H1|

if (H0 != H1?) then (not equal)
    :compute config4copy2.json Hash to H2|
    if (H0 == H2?) then (yes)
        :load config4.json to jsonData;
        note left
            copy1 ko
            master AND copy2 same
            very low probability
            <b>keep master
        end note
        #palegreen:fileLoaded = true;
    endif
    if (H1 == H2? ) then ( config4.json ko) 
        :load config4copy1.json to jsonData;
        note left
            copy 1 AND copy 2 same
            master ko 
            <b>keep copy
        end note
        #palegreen:fileLoaded = true;
    endif
else
    :load config4.json to jsonData;
    note right
        master AND copy 1 same
        and perhaps copy 2 also
        <b>keep master
    end note
    #palegreen:fileLoaded = true;
endif

if (fileLoaded?) is (<b>not loaded) then
#red:set error json file;
note left
    in this case H0 != H1 != H2
end note
endif

end

@enduml