@startuml

<style>
caption {
FontSize 20
}
</style>



caption Write events: web details (configuration)
actor web
participant handleIOTESPConfiguration
participant "ConfigParam:write2Json"
database SPIFFS #red
web -> handleIOTESPConfiguration: /cfgpage
note left
clic config buton
end note
loop For all parameters (confParam[9], plugsNickName[4], chekBoxes[4])
    handleIOTESPConfiguration -> "ConfigParam:write2Json":HTML_XXXX_PARAM
    activate "ConfigParam:write2Json"
    "ConfigParam:write2Json" -> SPIFFS:open
    "ConfigParam:write2Json" -> SPIFFS:read all
    "ConfigParam:write2Json" -> SPIFFS:write all
    "ConfigParam:write2Json" --> handleIOTESPConfiguration
    deactivate "ConfigParam:write2Json"
end

@enduml