@startuml
web -> config4.json: clic to config
plug -> config4.json: time To switch
bpLonClic -> config4.json: restaure file
web -> config4.json: clic to set plug
@enduml

@startuml
web -> handleIOTESPConfiguration: clic config buton
loop For all parameters (confParam[9], plugsNickName[4], chekBoxes[4])
    handleIOTESPConfiguration -> "ConfigParam:write2Json":HTML_XXXX_PARAM
    activate "ConfigParam:write2Json"
    "ConfigParam:write2Json" -> SPIFFS:open
    "ConfigParam:write2Json" -> SPIFFS:read all
    "ConfigParam:write2Json" -> SPIFFS:write all
    "ConfigParam:write2Json" --> handleIOTESPConfiguration
    deactivate "ConfigParam:write2Json"
end



@enduml